'''
# 389. Find the Difference

# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
'''
class leetcode389(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        letter_freq = {}
        for letter in s:
            if letter not in letter_freq:
                letter_freq[letter] = 1
            else:
                letter_freq[letter] += 1

        for letter in t:
            if letter in letter_freq:
                letter_freq[letter] -= 1
            else:
               return letter 

        #return list(letter_freq)[0]

        for letter in letter_freq:
            if letter_freq[letter] != 0:
                return letter

        #Alternatively, xor 0 and s+t 
